#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#rutas usuario
user:
    path: /user
    controller: App\Controller\UserController::index

create:
   path: /create
   controller: App\Controller\UserController::create
   methods: [POST]

login:
  path: /login
  controller: App\Controller\UserController::login
  methods: [POST]

user_edit:
  path: /user/edit
  controller: App\Controller\UserController::edit
  methods: [PUT]


#rutas video
video:
    path: /video
    controller: App\Controller\VideoController::index

video_new:
  path: /video/new
  controller: App\Controller\VideoController::create
  methods: [POST]

video_list:
  path: /video/list
  controller: App\Controller\VideoController::videos
  methods: [GET]

video_detail:
  path: /video/detail/{id}
  controller: App\Controller\VideoController::detail
  methods: [GET]

video_remove:
  path: /video/remove/{id}
  controller: App\Controller\VideoController::remove
  methods: [DELETE]

video_edit:
  path: /video/edit/{id}
  controller: App\Controller\VideoController::create
  methods: [PUT]